 /******************************************************************************
 *
 * Module:Ultrasonic sensor HC-SR04
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the Ultrasonic sensor HC-SR04 driver
 *
 * Author: Shimaa Gamal
 *
 *******************************************************************************/


#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define TR_PORT_ID                PORTB_ID
#define TR_PIN_ID                 PIN5_ID



/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * 1-initialize the ICU driver as required.
 * 2-Setup the ICU call back function.
 * 3-Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the Ultrasonic.
 */

void Ultrasonic_Trigger(void);

/*
 * Description :
 * 1-Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2-Start the measurements by the ICU from this moment
 */


uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * 1-This is the call back function called by the ICU driver.
 * 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing (void);




#endif /* ULTRASONIC_H_ */
